spring.application.name=school_Management_Backend
# 1. Connexion à la base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/school_management_db
spring.datasource.username=postgres
spring.datasource.password=musafa

# 2. Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Stratégie de génération des tables (Hibernate)
# 'update' permet de créer ou modifier les tables automatiquement selon tes classes Java
spring.jpa.hibernate.ddl-auto=update

# 4. Affichage des requêtes SQL dans la console (Utile pour le debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 5. Dialecte SQL pour PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springdoc=DEBUG

# La clé de sécurité pour les badges (Tokens)
# Elle doit être longue, complexe et rester secrète !
school.app.jwtSecret=CeciEstUneCleTresLongueEtSecuriseePourLeSystemeDeGestionScolaireMUSAFA2026
# Expiration : 24 heures (en millisecondes)
school.app.jwtExpirationMs=86400000

# Taille maximale autorisée pour un seul fichier
spring.servlet.multipart.max-file-size=50MB

# Taille maximale totale autorisée pour une requête (somme de tous les fichiers + données)
spring.servlet.multipart.max-request-size=100MB
