spring.application.name=school_Management_Backend

# 1. Connexion a la base de donnees
# En local : utilise localhost. En production : utilisera la variable d'environnement DB_URL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/school_management_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:musafa}

# 2. Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Strategie de generation des tables (Hibernate)
spring.jpa.hibernate.ddl-auto=update

# 4. Affichage des requetes SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 5. Dialecte SQL pour PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springdoc=DEBUG

# La cle de securite pour les badges (Tokens)
# Utilise une variable d'environnement pour la production, sinon la valeur par d\u00E9faut pour le local
school.app.jwtSecret=${JWT_SECRET:CeciEstUneCleTresLongueEtSecuriseePourLeSystemeDeGestionScolaireMUSAFA2026}

# Expiration : 24 heures (en millisecondes)
school.app.jwtExpirationMs=86400000

# Taille maximale autorisee pour un seul fichier
spring.servlet.multipart.max-file-size=50MB

# Taille maximale totale autorisee pour une requete
spring.servlet.multipart.max-request-size=100MB